[package]
name = "bitcoin-p2p-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
bitcoin = "0.32"
rand = "0.8"
tokio = { version = "1", features = ["full"] }
log = "0.4"
pretty_env_logger = "0.5"
