services:
  btcliked:
    image: ruimarinho/bitcoin-core:22.0
    command: "bitcoind -regtest=1 -rpcallowip=0.0.0.0/0 -rpcbind=0.0.0.0 -rpcuser=user -rpcpassword=pass -fallbackfee=0.001 -deprecatedrpc=addresses -txindex -capturemessages=1 -debug=net"
    ports: 
      - "18443:18443"
      - "18444:18444"
